# Change these first
owner: ialopezc # Your GitHub organization or username, where this repository lives
repo: upptimeSuntech # The name of this repository
user-agent: ialopezc

sites:
  - name: MONITOR
    url: https://demo.imovit.net/
  - name: WEBAPP
    url: https://demo.imovit.net/webApp/
  - name: SIAD
    url: https://siad.imovit.net/
  - name: CONTROL
    url: https://democontrol.imovit.net/

  - name: MONITOR staging
    url: https://awsdev.imovit.net/
    hidden: true
  - name: WEBAPP staging
    url: https://awsdev.imovit.net/webApp/
    hidden: true
  - name: SIAD staging
    url: https://siaddev.imovit.net/
    hidden: true
  - name: CONTROL staging
    url: https://awsdevcontrol.imovit.net/
    hidden: true

  - name: SCUTI Prod
    url: https://www.suntechscuti.com/scuti/
    check: "http-ping"
    # skip-ssl: true
    # headers:
    #   - key: "User-Agent"
    #     value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    expected-status-code: 200
  - name: SCUTI Brasil
    url: https://scuti.suntechdobrasil.com.br/
    check: "http-ping"
    skip-ssl: true
    # headers:
    #   - key: "User-Agent"
    #     value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    expected-status-code: 200

  - name: SCUTI Dev
    url: http://scutidevelop.suntechlatam.com/
    hidden: true
  - name: SCUTI Test
    url: https://scutitest.suntechlatam.com/
    hidden: true


assignees: # Usuarios para asignar problemas de tiempo de inactividad
  - ilopezSTI
  - danielaCamacho53
  - eduardomartinezsti

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: ialopezc.github.io
  baseUrl: /upptimeSuntech

logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
name: upptimeSuntech
introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
navbar:
  - title: Status
    href: /
  - title: GitHub
    href: https://github.com/ialopezc/upptimeSuntech

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

notifications:
  - type: email
    to:
      - carlos.hernandez@suntechlatam.com
      - daniela.camacho@suntechlatam.com
      - eduardo.martinez@stisolutions.com.mx
